# Generated by Django 2.2.9 on 2020-02-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
