# Generated by Django 2.2.9 on 2020-02-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeses', '0002_memes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='slug',
        ),
    ]
