# Generated by Django 2.2.9 on 2020-02-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeses', '0004_memes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
