# Generated by Django 2.2.9 on 2020-04-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeses', '0005_auto_20200201_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
